apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgB+Ew97HzX4yVLgBi+FXh4PaHyb6TIuGML2ZcBoinyAybuikT/SErIqw/vr67SJURrxGyp4bcluYlHThFHGFlcQ2i84Xg+allSKbG1o3CQKVD3Rc3Lor1bzbjImGQUKpkEj6oRxry/tu/mnMjIRbZph27zFpXIcmfAoYtrGbZ+LFZh0z16Vglmp9FV9jhKs0Zw7znoFNVmjyHk6kqBZ2be1FxgDzzwJBs+pgZE96AelHaHzbafGbCbMPNWH3fBR/KsG9RW24BIm0qqgqymp3iAhfEWn4eKh3StownECjYyz8L0iSv1ocGnby/lJkkkbT3F3Pb+RK5p7DrCuC41u1v+3ZXoeiITE3n5R3Ub8HXQmLIpAQxfybwcWVs5xVLwE/T5BNOAJR3sHJxTHqUvY7VFEMAoygu1uj/I//8AVleW7RIHFh2uXpE77IJK3ZJUYpdbgoRASp6ji3Nvx/GfYyvDDLTttqIXmzBr2vJWrGMX4dm6Oi3vJY4IQyLSLE4kuUml93IFWzAFpq1w9/tGQV66tNy3H00hGdm6eHgsC5zJcUVA2t5dz6xzM/PozQ6SuDK5GvGF32otBe2CW5zlGnlzerjJs5EUqiC72rkPOw2ALz4K8Me/DIZf81pjNFTr0MH7BelyISHaHUFv2xym2LOPqAPqtXWIAhJQj5MgXcW+FhGZLez4mnqCHM5Ljw/Fp0IQPp5rnwSUxvB8x20wBxPftWlWyyVSC5hDKEVpQMC3Tfj+C5+IHHfHScL5b8eo873xAAEriz9SXVUKxrj22Vtqi+XprIqWIWsHic0cCpCQYYwYFMMrYV/zQ82WmI7Bb/sGnqhRE+fv960kjhnhCxuTixMTNgRiIcFakAlYOh2fhP3jdQ/ZjlDTM1rJMf11qdhmAPa5dzTZn/spmAFEDBBoCDFSINJ/m8dn1nJZMdgzRK7SPNyTvILBTSmp0Ga2wMqY=
    IBM_ENTITLED_REGISTRY_USER: AgBze73Z5WixSRczVLXFkICOpxWVr11fVySaPSORqpcngHA60I/DnvVioVHG2UimowCuW+UHQW1Obc+2xUoq37gFPKqGXEtUAzXBH+Fw3NI2F6scNZZqYqXiUH6aaqJqOIMJpotx0Raiurlrz3Q0i0UEYz7rPhHcHdYCXa6wUqONFqaZTWzBdaejzRQTvuQrr4um0EZr3jeGyjrH7/Y90/0NAtB4kHDnURCRvFnx73RsgNPy3X8GYuKKPGGSicEVjbyCtudDAJ0yJt+67fQBVB5zDKMB8i6OQyFAHltq5hlBNGNiLck4AE68/FglALnNQhdMAEru1m545mLX2Nq2TO0qv/xmffKiwKqxyDvem7oSDJAvC02cBxw9pmJYsRoZwyfvJNBuk68Ety+/7ctlwbQ2MVdD0R5zPJi32Frzaxjb1xcgbeokkK4j0IR4TcokS2S9nXVNRiQqus+2CZ4yJZLXOQSZmRBo03rgm+bRDiKqJKpNPONVhLAnWn3xrbjhUd4CH0cdcPgYMIqkdx8AJP1iCAaBZXOYe7csv1rD0HgsES7SpOKmKkaH6/Y7nuXv26NT2X9nxVcEB8TOdUUp/87F6uTO6AXs3pNbvOHahDF3BuWTng4FrWwO/pPsCgnyG/VcaHw3Rpekbnm60JRCIj4EiRElUuFrl7hzF1y7p4RO79KshfQK0zz0YRZ5PhlU76udHw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

